name: funk
description: funk UI
version: 0.1.0
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Source Code Pro
      fonts:
        - asset: packages/funk/fonts/SourceCodePro-Regular.ttf
        - asset: packages/funk/fonts/SourceCodePro-Bold.ttf
          weight: 700
        - asset: packages/funk/fonts/SourceCodePro-SemiBold.ttf
          weight: 600   
        - asset: packages/funk/fonts/SourceCodePro-Medium.ttf
          weight: 500                  
        - asset: packages/funk/fonts/SourceCodePro-Light.ttf
          weight: 300
        - asset: packages/funk/fonts/SourceCodePro-ExtraLight.ttf
          weight: 200